services:
  - type: web
    name: safetour-server
    env: node
    runtime: node
    nodeVersion: 18.x
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true